name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Middle job
        run: |
          echo "Step 1"
          echo "Step 2"
      - name: Print goodbye
        run: echo "Done, bye!"
